In [1]:
import torch

In [2]:
x = torch.Tensor([5,3])

y = torch.Tensor([2,3])


In [3]:
print(x*y)

tensor([10.,  9.])


In [4]:
x

tensor([5., 3.])

In [5]:
y

tensor([2., 3.])

In [6]:
x.shape

torch.Size([2])

In [7]:
y = torch.rand([2,5])

In [8]:
y

tensor([[0.5008, 0.4134, 0.1057, 0.8202, 0.7241],
        [0.0542, 0.3321, 0.2211, 0.7262, 0.9782]])